#  ____  _               _    ____ ___
# | __ )| |_   _  ___   / \  |  _ |_ _|
# |  _ \| | | | |/ _ \ / _ \ | |_) | |
# | |_) | | |_| |  __// ___ \|  __/| |
# |____/|_|\__,_|\___/_/   \_|_|  |___|

config_version: 100

# Metrics:
# This plugin uses the bStats metrics system. If you want your data not to be collected, you can disable this system here.
# The following information is collected and sent to bstats.org:
#      Whether the server is in offline or online mode
#      The plugin version
#      The server version
#      The java version
#      The OS version/name and architecture
#      The location of your server
#      The core count for the CPU
#      The number of players online
#      The Metrics version
metrics: true